(define play (lambda (fname)
	       (let* ((net (filternetwork_new "play" "plays files"))
		       (rf (filternetwork_add_node net "read_file" "readfile"))
		       (ao (filternetwork_add_node net "audio_out" "aout")))
		  (filternode_set_param rf "filename" fname)
		  (filternetwork_add_connection rf "out" ao "in")
		  (filternetwork_add_connection rf "out" ao "in")
		  (filternetwork_launch net)
		  (filternetwork_start net)
		  (filternetwork_wait net)
		  (filternetwork_delete net))
	       )
)
