@comment $Id: plugins.texi,v 1.6 2000/04/04 19:03:01 nold Exp $

@node Plugin Collection, Filter API, Console Frontend, Top
@chapter Plugin Collection

@comment TODO: Which index should I list the plugins in?

Available GLAME plugins are listed here with a short description about what
they are able to do, their input and output ports, and the parameters 
they understand. Some ports allow more than one so-called pipe to be
connected. Those restrictions will be listed in the port description. 
Some parameters can be set per plugin, some per pipe. Pipe parameters are
listed with the name of the pipe preceeding the parameter name, separated
by a double colon, like @code{out::position} for parameter @code{position}
on pipe @code{out}. Each parameter is followed by its type--e.g. integer,
float, or string--in parentheses.

@menu
* Audio I/O::
* File I/O::
* Elementary Plugins::
* Effects::
@end menu

@node Audio I/O, File I/O,, Plugin Collection
@section Audio I/O

The @file{audio-in} and @file{audio-out} plugins handle communication between 
GLAME and the sound hardware. @file{audio-in} is for recording, 
@file{audio-out} does the playback. 
Actually, there are several instances of those plugins for different sound
systems like ESD, ALSA, OSS, and native SGI. If available on the system, 
they can be accessed directly via @file{oss-audio-out}, @file{esd-audio-in} 
and the like, using the same sets of parameters. Think of @file{audio-in} and 
@file{audio-out} as sane default methods dependent on the system's capabilities.

@subheading Common parameters
@table @code
@item device (string)
Sound device to be used. Note: While audio-in and audio-out are generic plugins,
interpretation of the device parameter is dependent on the underlying sound
system which the value is passed to unmodified. For example, OSS takes devices
parameters like @file{/dev/dsp} where ALSA would like @code{0:0}.
@end table

@subheading @file{audio-in} ports
@table @code
@item out (output)
Recorded stream of sample data. Maximum number of allowed out-connections 
depends on hardware capabilities.
@end table

@subheading @file{audio-in} parameters
@table @code
@item rate (integer)
The sample rate in Hertz.
@item duration (float)
Recording time in seconds.
@item out::position (float)
Horizontal placement of sample stream in radians from -pi to pi.
@end table

@subheading @file{audio-out} ports
@table @code
@item in (input)
Sample stream to play back. Maximum number of allowed in-connections
depends on hardware capabilities.
@end table

@file{audio-out} has no further specific parameters.


@node File I/O, Elementary Plugins, Audio I/O, Plugin Collection
@section File I/O
Transactions from and to files are handled by the plugins @file{read-file}
and @file{write-file}. @file{read-file} is guaranteed to be able to read
WAV files. Anything else is up to helper libraries that may or may not be
installed on a system. @file{write-file} so far only second guesses the
desired output format from the suffix of the given filename.

@subheading Common parameters
@table @code
@item filename (string)
Name of the file to be read from or written to. The writer takes the
filename suffix as a hint to the desired type of output.
@end table

@subheading @file{read-file} ports
@table @code
@item out (output)
Sample data read in from a sound file. The number of allowed out-connections
varies from file to file.
@end table

@subheading @file{read-file} parameters
@table @code
@item out::position (float)
Horizontal placement of sample stream in radians from -pi to pi.
@end table

@subheading @file{write-file} ports
@table @code
@item in (input)
Sample stream to store to a sound file. Maximum number of allowed in-connections
depends on the desired sound format.
@end table

@file{write-file} has no further specific parameters.

@node Elementary Plugins, Effects, File I/O, Plugin Collection
@section Elementary Plugins

TODO: mul, add, phase-invert (arithmetic.c), 
volume-adjust, delay, extend, repeat (basic_sample.c),
ping (debug.c), echo (echo.c), pan (pan.c), pipe-in (pipe.c),
statistic, debugrms (rms.c), track-in, track-out (track_io.c), 
null, dup (tutorial.c), sinus [*** Doh! Rename to sine! ***], const (waveform.c)

*** Add them here first. Will move to new sections as appropriate. ***

@menu 
* Junctions and Dead Ends::
@end menu

@node Junctions and Dead Ends,,, Elementary Plugins
@subsection Junctions and Dead Ends

In a filter network, data streams don't get created from nowhere, neither
do they disappear into a big black void: there must be a plugin at each
endpoint of a connection. These Plugins in turn are allowed to dump data or
create new streams.

The @file{drop} plugin is used as a sink for data that is no longer needed 
within the network. Any incoming data is simply discarded. It's the dead
end of a network.

If the same stream of data is needed more than once, it cannot simply be 
applied several times to different ports, it has to be duplicated first. 
@file{one2n} is the plugin to perform this task, it forks the network, so
to speak.

@file{mix} on the other hand acts as a junction and merges several data
streams into one, just like an ordinary mixing desk. The @file{mix} plugin
comes in two flavours, @file{mix}, and @file{mix2}. The only time to worry
about the differences is when you want to create loops in your network: 
@file{mix} drops all input data after the first input stream has terminated,
@file{mix2} continues to mix available inputs instead. Otherwise @file{mix}
and @file{mix2} are identical. Use @file{mix} for mixing feedback.

@subsubheading @file{drop} ports
@table @code
@item in (input)
Data to be dropped. Any number of input connections is allowed.
@end table

@file{drop} has no parameters.

@subsubheading @file{one2n} ports
@table @code
@item in (input)
Stream to be replicated.
@item out (output)
Replicated stream. Any number of output connections is allowed.
@end table

@file{one2n} has no parameters.

@subsubheading @file{mix} ports
@table @code
@item in (input)
Audio streams to be mixed. Any number of input connections is allowed.
@item out (output)
Mixed audio stream.
@end table

@subsubheading @file{mix} parameters
FIXME: Must become more descriptive. Add value ranges etc.
@table @code
@item in::gain (float)
Gain of the input.
@item in::offset (time)
Offset of the input data.
@item gain (float)
Gain of the output.
@item phi (float)
Position of the output.
@end table

@node Effects,, Elementary Plugins, Plugin Collection
@section Effects

TODO: noisegate (noisegate.c), iir (iir.c)

