(let ((newplugin (glame_plugin_define (let* ((net (filter-new))
	(Resample-1 (filter-add-node net (filter-new (plugin_get "Resample")) "Resample-1"))
	(Resample (filter-add-node net (filter-new (plugin_get "Resample")) "Resample"))
	(render (filter-add-node net (filter-new (plugin_get "render")) "render"))
	(pipe_out (filter-add-node net (filter-new (plugin_get "pipe_out")) "pipe_out")))
   ((lambda (pdb)
  (let* ((params (map (lambda (param)
		         (cons (param-label param) param))
		       pdb))
	  (pairs (map (lambda (spec)
		        (let ((p (assoc (car spec) params)))
			     (if p
			       (cons (cdr p) (cdr spec))
			       (throw 'glame-error))))
                     (list (append (list "frequency" 44100) (list (cons "_desc" "new sample frequency") (cons "_node" "fft_resample") (cons "_label" "frequency")))
        ))))
        (for-each
          (lambda (p)
            (param-set! (car p) (cadr p))
            (for-each
              (lambda (prop)
                (set-property! (car p) (car prop) (cdr prop)))
              (cddr p)))
          pairs)))
 (filter-params Resample-1))
   (for-each
     (lambda (p)
       (set-property! Resample-1 (car p) (cdr p)))
     (list (cons "selected" "0") (cons "canvas_y" "73.0") (cons "canvas_x" "24.0")))
   ((lambda (pdb)
  (let* ((params (map (lambda (param)
		         (cons (param-label param) param))
		       pdb))
	  (pairs (map (lambda (spec)
		        (let ((p (assoc (car spec) params)))
			     (if p
			       (cons (cdr p) (cdr spec))
			       (throw 'glame-error))))
                     (list (append (list "frequency" 44100) (list (cons "_desc" "new sample frequency") (cons "_node" "fft_resample") (cons "_label" "frequency")))
        ))))
        (for-each
          (lambda (p)
            (param-set! (car p) (cadr p))
            (for-each
              (lambda (prop)
                (set-property! (car p) (car prop) (cdr prop)))
              (cddr p)))
          pairs)))
 (filter-params Resample))
   (for-each
     (lambda (p)
       (set-property! Resample (car p) (cdr p)))
     (list (cons "selected" "0") (cons "canvas_y" "-22.0") (cons "canvas_x" "24.0")))
   (for-each
     (lambda (p)
       (set-property! render (car p) (cdr p)))
     (list (cons "selected" "0") (cons "canvas_y" "17.0") (cons "canvas_x" "-227.0")))
   ((lambda (pdb)
  (let* ((params (map (lambda (param)
		         (cons (param-label param) param))
		       pdb))
	  (pairs (map (lambda (spec)
		        (let ((p (assoc (car spec) params)))
			     (if p
			       (cons (cdr p) (cdr spec))
			       (throw 'glame-error))))
                     (list (append (list "cmd" "lame -r -x - ") (list (cons "_desc" "command string")))
        ))))
        (for-each
          (lambda (p)
            (param-set! (car p) (cadr p))
            (for-each
              (lambda (prop)
                (set-property! (car p) (car prop) (cdr prop)))
              (cddr p)))
          pairs)))
 (filter-params pipe_out))
   (for-each
     (lambda (p)
       (set-property! pipe_out (car p) (cdr p)))
     (list (cons "selected" "1") (cons "canvas_y" "22.0") (cons "canvas_x" "221.0")))
   (filternetwork_add_input net render "in" "in" "in")
   (filternetwork_add_param net pipe_out "tail" "filename" "(null)")
   (let ((pipe (filter-connect Resample-1 "out" pipe_out "in")))
	#t)
   (let ((pipe (filter-connect Resample "out" pipe_out "in")))
	#t)
   (let ((pipe (filter-connect render "out" Resample-1 "in")))
       ((lambda (pdb)
  (let* ((params (map (lambda (param)
		         (cons (param-label param) param))
		       pdb))
	  (pairs (map (lambda (spec)
		        (let ((p (assoc (car spec) params)))
			     (if p
			       (cons (cdr p) (cdr spec))
			       (throw 'glame-error))))
                     (list (append (list "position" 1.571) (list))
        ))))
        (for-each
          (lambda (p)
            (param-set! (car p) (cadr p))
            (for-each
              (lambda (prop)
                (set-property! (car p) (car prop) (cdr prop)))
              (cddr p)))
          pairs)))
 (pipe-source-params pipe))
	#t)
   (let ((pipe (filter-connect render "out" Resample "in")))
       ((lambda (pdb)
  (let* ((params (map (lambda (param)
		         (cons (param-label param) param))
		       pdb))
	  (pairs (map (lambda (spec)
		        (let ((p (assoc (car spec) params)))
			     (if p
			       (cons (cdr p) (cdr spec))
			       (throw 'glame-error))))
                     (list (append (list "position" -1.571) (list))
        ))))
        (for-each
          (lambda (p)
            (param-set! (car p) (cadr p))
            (for-each
              (lambda (prop)
                (set-property! (car p) (car prop) (cdr prop)))
              (cddr p)))
          pairs)))
 (pipe-source-params pipe))
	#t)
   net)
 "write_mp3")
)) (if (filter? newplugin) newplugin (plugin-set! newplugin PLUGIN_CATEGORY "Output")))
